MotorsUp_/Models/DetalleCompra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MotorsUp_.Models
{
    public partial class DetalleCompra
    {
        public int IdDetalleCompra { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "El precio debe ser de tipo numerico")]
        public float Precio { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [RegularExpression(@"^\d+$", ErrorMessage = "La cantidad debe ser de tipo numerico")]
        public int Cantidad { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [RegularExpression(@"^\d*\.?\d*$", ErrorMessage = "El subtotal debe ser de tipo numerico")]
        public float Subtotal { get; set; }
        public int IdCompra { get; set; }
        public int IdProducto { get; set; }

        public virtual Compra? IdCompraNavigation { get; set; } = null!;
        public virtual Producto? IdProductoNavigation { get; set; } = null!;
    }
}

MotorsUp_/Controllers/DetalleComprasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using System.Linq;
using System.Threading.Tasks;
using iText.Kernel.Colors;
using iText.Layout.Renderer;
using iText.Kernel.Pdf.Canvas;
using iText.IO.Image;
using System;
using OfficeOpenXml;
using System.IO;
using System.Collections.Generic;
using MotorsUp_.Models;
namespace MotorsUp_.Controllers
{
    public class DetalleComprasController : Controller
    {
        private readonly tallerContext _context;
       

        public DetalleComprasController(tallerContext context)
        {
            _context = context;
        }

        // GET: DetalleCompras
        public async Task<IActionResult> Index()
        {
            var tallerContext = _context.DetalleCompras.Include(d => d.IdCompraNavigation).Include(d => d.IdProductoNavigation);
            return View(await tallerContext.ToListAsync());
        }

        // GET: DetalleCompras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DetalleCompras == null)
            {
                return NotFound();
            }

            var detalleCompra = await _context.DetalleCompras
                .Include(d => d.IdCompraNavigation)
                .Include(d => d.IdProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalleCompra == id);
            if (detalleCompra == null)
            {
                return NotFound();
            }

            return View(detalleCompra);
        }

        // GET: DetalleCompras/Create
        public IActionResult Create()
        {
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra");
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto");
            return View();
        }

        // POST: DetalleCompras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdDetalleCompra,Precio,Cantidad,Subtotal,IdCompra,IdProducto")] DetalleCompra detalleCompra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detalleCompra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            if (!ModelState.IsValid)
            {
                ViewData["Error"] = "Datos incorectos";
                return View();
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            return View(detalleCompra);
        }

        // GET: DetalleCompras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DetalleCompras == null)
            {
                return NotFound();
            }

            var detalleCompra = await _context.DetalleCompras.FindAsync(id);
            if (detalleCompra == null)
            {
                return NotFound();
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            return View(detalleCompra);
        }

        // POST: DetalleCompras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdDetalleCompra,Precio,Cantidad,Subtotal,IdCompra,IdProducto")] DetalleCompra detalleCompra)
        {
            if (id != detalleCompra.IdDetalleCompra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalleCompra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleCompraExists(detalleCompra.IdDetalleCompra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCompra"] = new SelectList(_context.Compras, "IdCompra", "IdCompra", detalleCompra.IdCompra);
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "IdProducto", detalleCompra.IdProducto);
            return View(detalleCompra);
        }

        // GET: DetalleCompras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DetalleCompras == null)
            {
                return NotFound();
            }

            var detalleCompra = await _context.DetalleCompras
                .Include(d => d.IdCompraNavigation)
                .Include(d => d.IdProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdDetalleCompra == id);
            if (detalleCompra == null)
            {
                return NotFound();
            }

            return View(detalleCompra);
        }

        // POST: DetalleCompras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DetalleCompras == null)
            {
                return Problem("Entity set 'tallerContext.DetalleCompras'  is null.");
            }
            var detalleCompra = await _context.DetalleCompras.FindAsync(id);
            if (detalleCompra != null)
            {
                _context.DetalleCompras.Remove(detalleCompra);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DetalleCompraExists(int id)
        {
            return (_context.DetalleCompras?.Any(e => e.IdDetalleCompra == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> GenerarReportePDF()
        {
            var detallesCompra = await _context.DetalleCompras.ToListAsync();

            MemoryStream memoryStream = new MemoryStream();
            PdfWriter writer = new PdfWriter(memoryStream);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);


            Paragraph titulo = new Paragraph("Reporte Detalle de Compras").SetTextAlignment(TextAlignment.CENTER);
            document.Add(titulo);


            document.Add(new Paragraph("\n"));


            Div div = new Div().SetHorizontalAlignment(HorizontalAlignment.CENTER);


            Table table = new Table(3);
            table.AddHeaderCell("Precio");
            table.AddHeaderCell("Cantidad");
            table.AddHeaderCell("Subtotal");


            foreach (var detalleCompra in detallesCompra)
            {
                table.AddCell(detalleCompra.Precio.ToString());
                table.AddCell(detalleCompra.Cantidad.ToString());
                table.AddCell(detalleCompra.Subtotal.ToString());
            }


            div.Add(table);


            document.Add(div);
            document.Close();

            return File(memoryStream.ToArray(), "application/pdf", "ReporteDetallesCompra.pdf");
        }

        public async Task<IActionResult> GenerarReporteExcelConGrafico()
        {
            var detallesCompra = await _context.DetalleCompras.ToListAsync();

             ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("ReporteCompras");

                // Agregar datos de las compras al archivo Excel
                worksheet.Cells[1, 1].Value = "Precio";
                worksheet.Cells[1, 2].Value = "Cantidad";
                worksheet.Cells[1, 3].Value = "Subtotal";

                int row = 2;
                foreach (var detalleCompra in detallesCompra)
                {
                    worksheet.Cells[row, 1].Value = detalleCompra.Precio;
                    worksheet.Cells[row, 2].Value = detalleCompra.Cantidad;
                    worksheet.Cells[row, 3].Value = detalleCompra.Subtotal;
                    row++;
                }

                // Crear un gráfico con los datos
                var chart = worksheet.Drawings.AddChart("ChartTitle", OfficeOpenXml.Drawing.Chart.eChartType.ColumnClustered);
                chart.SetPosition(1, 0, 5, 0);
                chart.SetSize(600, 400);
                chart.Series.Add(worksheet.Cells["B2:B" + (row - 1)], worksheet.Cells["A2:A" + (row - 1)]);

                return File(package.GetAsByteArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteCompras.xlsx");
            }

        }

    }
}

MotorsUp_/Views/DetalleCompras/Create.cshtml
@model MotorsUp_.Models.DetalleCompra

@{
    ViewData["Title"] = "Create";
}


<h4 class="row justify-content-center"> Añadir detalle compra</h4>
<a asp-action="Index" style="text-decoration: none;"><i class="bi bi-arrow-left-square-fill"></i></a>

<div class="row">
    <div class="col-md-4" >
        <form asp-action="Edit" id="form-detalle-compra">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" id="precio"/>
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" id="cantidad"/>
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" id="subtotal"/>
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCompra" class="control-label"></label>
                <select asp-for="IdCompra" class="form-control" asp-items="ViewBag.IdCompra"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdProducto" class="control-label"></label>
                <select asp-for="IdProducto" class="form-control" asp-items="ViewBag.IdProducto"></select>
            </div>
            <div class="content-button">
                <div class="form-group text-center" style="padding: 7px">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        document.getElementById('form-detalle-compra').addEventListener('submit', function (e) {
            e.preventDefault();
            // Obtener los valores directamente y validar
            if (
                document.getElementById('precio').value.trim() !== '' &&
                document.getElementById('cantidad').value.trim() !== '' &&
                document.getElementById('subtotal').value.trim() !== '' &&
                document.getElementById('IdCompra').value.trim() !== '' &&
                document.getElementById('IdProducto').value.trim() !== ''
            ) {
                swal.fire({
                    title: 'Detalle de compra registrado con éxito',
                    icon: 'success',
                    showConfirmButton: false,
                    showCancelButton: false,
                    timer: 1800
                }).then(() => {
                    document.getElementById('form-detalle-compra').submit();
                });
            } else {
                swal.fire({
                    title: 'Complete todos los campos',
                    icon: 'warning',
                    showConfirmButton: false,
                    showCancelButton: false,
                    timer: 1800
                });
            }
        });

    </script>
}

MotorsUp_/Views/DetalleCompras/Delete.cshtml
@model MotorsUp_.Models.DetalleCompra

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetalleCompra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCompraNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCompraNavigation.DescripcionCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdDetalleCompra" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MotorsUp_/Views/DetalleCompras/Details.cshtml
@model MotorsUp_.Models.DetalleCompra

@{
    ViewData["Title"] = "Details";
}

<h1 class="row justify-content-center">Detalles de compras</h1>
<a asp-action="Index" style="text-decoration: none;"><i class="bi bi-arrow-left-square-fill"></i></a>

<div class="row justify-content-center" style="padding:10px">
    <table>
        <thead>
            <tr>
                <th scope="col">Id detalle compra</th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad </th>
                <th scope="col">Subtotal </th>
                <th scope="col">Id compra</th>
                <th scope="col">Id producto</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.IdDetalleCompra)</td>
                <td>@Html.DisplayFor(model => model.Precio)</td>
                <td>@Html.DisplayFor(model => model.Cantidad)</td>
                <td>@Html.DisplayFor(model => model.Subtotal)</td>
                <td>@Html.DisplayFor(model => model.IdCompraNavigation.DescripcionCompra)</td>
                <td>@Html.DisplayFor(model => model.IdProductoNavigation.IdProducto)</td>
                <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.IdDetalleCompra"><i class="bi bi-pencil-square"></i></a>

                </td>
            </tr>
        </tbody>
    </table>
</div>

MotorsUp_/Views/DetalleCompras/Edit.cshtml
@model MotorsUp_.Models.DetalleCompra

@{
    ViewData["Title"] = "Edit";
}


<h4 class="row justify-content-center">Editar detalle de compra</h4>
<a asp-action="Index" style="text-decoration: none;"><i class="bi bi-arrow-left-square-fill"></i></a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="form-detalle-compra">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdDetalleCompra" />
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" id="precio" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" id="cantidad" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" id="subtotal" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCompra" class="control-label"></label>
                <select asp-for="IdCompra" class="form-control" asp-items="ViewBag.IdCompra"></select>
                <span asp-validation-for="IdCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProducto" class="control-label"></label>
                <select asp-for="IdProducto" class="form-control" asp-items="ViewBag.IdProducto"></select>
                <span asp-validation-for="IdProducto" class="text-danger"></span>
            </div>
            <div class="content-button">
                <div class="form-group text-center" style="padding: 7px">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        document.getElementById('form-detalle-compra').addEventListener('submit', function (e) {
            e.preventDefault();
            // Obtener los valores directamente y validar
            if (
                document.getElementById('precio').value.trim() !== '' &&
                document.getElementById('cantidad').value.trim() !== '' &&
                document.getElementById('subtotal').value.trim() !== '' &&
                document.getElementById('IdCompra').value.trim() !== '' &&
                document.getElementById('IdProducto').value.trim() !== ''
            ) {
                swal.fire({
                    title: '¿Está seguro?',
                    text: '¿Está seguro que quiere editar este detalle de compra?',
                    icon: 'info',
                    buttons: true,
                    dangerMode: false,
                    showCancelButton: true,
                }).then((confirmed) => {
                    if (confirmed.value) {
                        document.getElementById('form-detalle-compra').submit();
                    } else {
                        swal.fire('Cancelado', 'El detalle de compra no fue modificado', 'info');
                    }
                });
            } else {
                swal.fire({
                    title: 'Complete todos los campos',
                    icon: 'warning',
                    showConfirmButton: false,
                    showCancelButton: false,
                    timer: 1800
                });
            }

        });

    </script>
}

MotorsUp_/Views/DetalleCompras/Index.cshtml
@model IEnumerable<MotorsUp_.Models.DetalleCompra>

@{
    ViewData["Title"] = "Index";
}

<h1 class="row justify-content-center">Gestion detalles de compras</h1>

    
<div class="d-flex justify-content-between">
    <p class="btn btn-primary">
        <a asp-action="Create" style="color: white; text-decoration: none;"><i class="bi bi-plus"></i> Añadir</a>
    </p>
    <div class="content_acciones_descarha">
    <a asp-controller="DetalleCompras" class="btn btn-danger" asp-action="GenerarReportePDF"><i class="bi bi-file-earmark-pdf-fill"></i></a>
    <a asp-controller="DetalleCompras" class="btn btn-success" asp-action="GenerarReporteExcelConGrafico"><i class="bi bi-file-earmark-excel-fill"></i></a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCompraNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdProductoNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subtotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCompraNavigation.DescripcionCompra)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdProductoNavigation.IdProducto)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.IdDetalleCompra"><i class="bi bi-pencil-square"></i></a> 
                <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.IdDetalleCompra"><i class="bi bi-sliders"></i></a> 
                
                 
            </td>
        </tr>
}
    </tbody>
</table>